# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb-dev-helloworld',
                'doc_host': 'https://williebonavente.github.io',
                'git_url': 'https://github.com/williebonavente/nb-dev-helloworld',
                'lib_path': 'nb_dev_helloworld'},
  'syms': {'nb_dev_helloworld.core': {'nb_dev_helloworld.core.foo': ('core.html#foo', 'nb_dev_helloworld/core.py')}}}
